{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shiftpv.fullname" . }}-node-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shiftpv.labels" . | nindent 4 }}
    app.kubernetes.io/component: node
    shiftpv.io/metrics: "true"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "shiftpv.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: node
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
{{- end }}
