{{- if .Values.runtime.identityContract }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "shiftpv.fullname" . }}-helper
  labels:
    {{- include "shiftpv.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    resourceNames: ["kube-system"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["list"]
  - apiGroups: ["shiftpv.io"]
    resources: ["shiftpvpools", "shiftpvvolumes", "shiftpvmoves"]
    verbs: ["get", "list"]
  - apiGroups: ["shiftpv.io"]
    resources: ["shiftpvcleanups"]
    verbs: ["get"]
  - apiGroups: ["shiftpv.io"]
    resources: ["shiftpvcleanups/status"]
    verbs: ["update"]
{{- end }}
