{{- if and .Values.runtime.identityContract .Values.serviceAccount.helper.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shiftpv.helperServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shiftpv.labels" . | nindent 4 }}
{{- end }}
