apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "shiftpv.fullname" . }}-provisioner
  labels:
    {{- include "shiftpv.labels" . | nindent 4 }}
{{ include "shiftpv.bindingBody" (dict
  "root" .
  "kind" "ClusterRole"
  "name" (printf "%s-provisioner" (include "shiftpv.fullname" .))
  "serviceAccount" (include "shiftpv.controllerServiceAccount" .)) }}
