apiVersion: v1
kind: Service
metadata:
  name: {{ include "shiftpv.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shiftpv.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "shiftpv.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: controller
  ports:
    - name: https
      port: 443
      targetPort: webhook
